/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'NARENDARR' at '8/9/16 9:38 PM' with Gradle 2.14
 *
 * @author NARENDARR, @date 8/9/16 9:38 PM
 */
public class Library {
    String name;
    public boolean someLibraryMethod() {
        int a = 0;        
        return true;
    }
}
