import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'NARENDARR' at '8/9/16 9:38 PM' with Gradle 2.14
 *
 * @author NARENDARR, @date 8/9/16 9:38 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("Naren - someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
